# Generated by Django 5.2.16 on 2026-09-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_item_add_restriction_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_name',
            field=models.CharField(blank=True, max_length=69, null=True, verbose_name='test name'),
        ),
    ]
