# Generated by Django 5.2.16 on 2026-09-16 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_user_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test_name',
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('file_hash', models.CharField(max_length=64, verbose_name='file_hash')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='core.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('is_signed', models.BooleanField(verbose_name='is_signed')),
                ('eiDas', models.CharField(blank=True, max_length=128, null=True, verbose_name='eiDas')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='name')),
                ('surname', models.CharField(blank=True, max_length=64, null=True, verbose_name='surname')),
                ('auth_level', models.IntegerField(blank=True, null=True, verbose_name='auth_level')),
                ('id_level', models.IntegerField(blank=True, null=True, verbose_name='id_level')),
                ('date_signed', models.DateTimeField(blank=True, null=True)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.signature')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
