# Generated by Django 5.2.16 on 2026-09-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_user_test_name_signature_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='received',
            name='auth_level',
        ),
        migrations.RemoveField(
            model_name='received',
            name='eiDas',
        ),
        migrations.RemoveField(
            model_name='received',
            name='id_level',
        ),
        migrations.AddField(
            model_name='received',
            name='eIDAS_lvl_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='eIDAS_lvl_1'),
        ),
        migrations.AddField(
            model_name='received',
            name='eIDAS_lvl_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='eIDAS_lvl_2'),
        ),
        migrations.AddField(
            model_name='received',
            name='eIDAS',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='eIDAS'),
        ),
    ]
