# Generated by Django 5.2.16 on 2026-09-17 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_received_auth_level_remove_received_eidas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='file',
        ),
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('file_hash', models.CharField(max_length=64, verbose_name='file_hash')),
                ('eIDAS', models.CharField(blank=True, max_length=128, null=True, verbose_name='eIDAS')),
                ('eIDAS_lvl_1', models.IntegerField(blank=True, null=True, verbose_name='eIDAS_lvl_1')),
                ('eIDAS_lvl_2', models.IntegerField(blank=True, null=True, verbose_name='eIDAS_lvl_2')),
                ('date_signed', models.DateTimeField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False, verbose_name='is_signed')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='core.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Received',
        ),
        migrations.DeleteModel(
            name='Signature',
        ),
    ]
